# Generated by Django 3.0.8 on 2021-01-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210119_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_before',
            field=models.IntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена со скидкой'),
        ),
    ]
