# Generated by Django 3.0.8 on 2021-01-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210119_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
