# Generated by Django 3.0.8 on 2021-01-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(null=True, verbose_name='Крааткое описание'),
        ),
    ]
