# Generated by Django 3.0.8 on 2021-01-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210119_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.CharField(choices=[('нету', 'нету'), ('мало', 'мало'), ('есть', 'есть'), ('по запросу', 'по запросу')], default='есть', max_length=20, verbose_name='Наличие у поставщика'),
        ),
    ]
