# Generated by Django 3.0.8 on 2021-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена со скидкой'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='final_discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена со скидкой'),
            preserve_default=False,
        ),
    ]
