# Generated by Django 3.0.8 on 2021-01-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210119_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='final_discount_price',
            new_name='final_price_without',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='final_discount_price',
            new_name='final_price_without',
        ),
    ]
