# Generated by Django 3.0.8 on 2021-01-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210119_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_price_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Скидка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='final_price_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Скидка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price_without',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена без скидки'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='final_price_without',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена без скидки'),
        ),
    ]
