# Generated by Django 3.0.8 on 2021-01-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210119_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='final_price_discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='final_price_without',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='final_price_discount',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='final_price_without',
        ),
    ]
