# Generated by Django 3.0.8 on 2021-01-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new_feed_back', 'Новый вопрос'), ('in_progress', 'В обработке'), ('answered', 'Отвечен'), ('some_problems', 'Возникли проблемы')], default='new_feed_back', max_length=100, verbose_name='Статус вопроса'),
        ),
    ]
