# Generated by Django 3.0.8 on 2021-01-26 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20210126_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата вопроса'),
        ),
    ]
